version: '2.0'
services:
   mongo:
     image: mongo
     container_name: "mongodb"
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: root
     ports:
       - 27017:27017                               
